services:
  # Spring Boot Application - Auth Service
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.0.59:5432/exe_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=HoiLamChi123@

      # Redis configuration
      - SPRING_REDIS_HOST=redis-16915.crce178.ap-east-1-1.ec2.redns.redis-cloud.com
      - SPRING_REDIS_PORT=16915
      - SPRING_REDIS_USERNAME=default
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      
      # Brevo API configuration
      - BERVO_HOST=smtp-relay.brevo.com
      - BERVO_MAIL_PORT=587
      - BERVO_MAIL_USERNAME=${BREVO_EMAIL_USERNAME}
      - BERVO_MAIL_PASSWORD=${BREVO_EMAIL_PASSWORD}
      - BREVO_SENDER_EMAIL=${BREVO_SENDER_EMAIL}
      - BREVO_SENDER_NAME=${BREVO_SENDER_NAME}

#      xsmtpsib-2a6defc26fa374b89e76a410a339bede43328da3b95c8b4781465293c1c21074-f0sf28sWH10j2S7z
      # JVM Options
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      carenest-network:
        ipv4_address: 192.168.0.12
    volumes:
      - app-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Postgres Service
  postgres:
   image: postgres:16-alpine
   container_name: postgres
   restart: unless-stopped
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=HoiLamChi123@
     - POSTGRES_DB=exe_db
   ports:
     - "5432:5432"
   networks:
     carenest-network:
       ipv4_address: 192.168.0.59
   volumes:
     - postgres-data:/var/lib/postgresql/data
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U postgres"]
     interval: 10s
     timeout: 5s
     retries: 5

networks:
  carenest-network:
    external: true

volumes:
  app-logs:
    driver: local
  redis-data:
    driver: local
  postgres-data:
    driver: local