otp:
  hmacSecret: xkeysib-6abb7bbe2b97bfff14c1b7c275ab996c2f717a93

spring:
  profiles:
    active: docker
  application:
    name: authorize-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://cbt118e6h2ekj2.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dqfsb4tvidjit}
    username: ${SPRING_DATASOURCE_USERNAME:ud1hq49h2ce600}
    password: ${SPRING_DATASOURCE_PASSWORD:p25c85fe262a4ff6c0759177d20d0339fc72043ed122dffb53c1742b638e0b5aa}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true



  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis-16915.crce178.ap-east-1-1.ec2.redns.redis-cloud.com}
      port: ${SPRING_REDIS_PORT:16915}
      username: ${SPRING_REDIS_USERNAME:default}
      password: ${SPRING_REDIS_PASSWORD:g5hwRXMAcpX5G0pCHOZWUvcSwYYUne9e}
      timeout: 5000ms
      connect-timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 2000


resend:
  api:
    key: ${RESEND_API_KEY:re_gmGazWTr_KLrJaQVoAQxSWUP4eVqRMrnY}
    from-email: ${RESEND_FROM_EMAIL:noreply@otp.devnest.io.vn}
    from-name: ${RESEND_FROM_NAME:Care Nest}

jwt:
  secret: CA39C3A2A3D4654A764C8E724CB37114CF68D80A34057F06641A31E0A0A3BA86

server:
  port: 8080
  forward-headers-strategy: native
  use-forward-headers: true

app:
  version: 1.0.0
  response:
    auto-wrap: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
    org.springframework.boot.autoconfigure.data.redis: DEBUG

springdoc:
  swagger-ui:
    use-root-path: true
